#!/bin/bash
#
# Get efficient log output for all top-level git repositories in a directory

if [ -z "$1" ]
then
	lines=-1
else
	lines=$1
fi

for i in `ls`; do
	if [ -d "$i" ]
	then
		cd $i
		if [ -e ".git" ]
		then
			echo $i
			git log --oneline --all --graph --decorate $lines
			echo "--"
		fi
		cd ../
	fi
done
